### ISSUE TITLE
Returns pc unit

### ISSUE THREAD

**Issue by iamvdo** [ben-eb/postcss-convert-values#11]
Weird behavior. See: https://github.com/robwierzbowski/node-pixrem/issues/42

**Comment by TrySound** [comment]
@eltonmesquita Give me please before and after code.

**Comment by iamvdo** [comment]
I tested using grunt-postcss's README example config.

in:
```
.my-class { min-height: 9rem; padding-bottom: 1rem; }
```

out:
```
.my-class { min-height: 9pc; min-height: 9rem; padding-bottom: 1pc; padding-bottom: 1rem; }
```

**Comment by ben-eb** [comment]
Think this is expected behaviour. Given the logic of what pixrem does https://github.com/robwierzbowski/node-pixrem/blob/master/lib/pixrem.js#L152-L154, it multiplies a rem value by 16 to create a pixel value. So your `9rem` becomes `144px`. Then, postcss-convert-values will take that value and *divide* it by 16 to get `9pc`. `1pc` equals `16px` so it follows that `9pc` is `144px`.

**Comment by iamvdo** [comment]
I better understand.
But print units (cm, mm, in, pt and pc) are not recommended for use on screen.

**Comment by ben-eb** [comment]
[From the spec](http://www.w3.org/TR/css3-values/#absolute-lengths):

> The _**absolute length units**_ are fixed in relation to each other and...these dimensions are either anchored (i) by relating the physical units to their physical measurements, or (ii) by relating the pixel unit to the reference pixel. For print media and similar high-resolution devices, the anchor unit should be one of the standard physical units (inches, centimeters, etc). For lower-resolution devices, and devices with unusual viewing distances, it is recommended instead that the anchor unit be the pixel unit. For such devices it is recommended that the pixel unit refer to the whole number of device pixels that best approximates the reference pixel.

And at least in my own browser testing I observed that using these alternative units over pixels didn't make a difference - as in screen media, the reference unit *is* the pixel, so the other absolute units are relative to that.

**Comment by iamvdo** [comment]
No problem, it was just an advice. :)
However, there used to be differences, see capture from CSS Tricks:
![image](https://cloud.githubusercontent.com/assets/1260529/9247051/8a532ef2-41b0-11e5-8f3f-f47180dcb820.png)

**Comment by TrySound** [comment]
@iamvdo I'm not sure ie tester can be objective.

**Comment by ben-eb** [comment]
I had thought about perhaps making these conversions optional, but I haven't had any bug reports like your example. :smile:

**Comment by iamvdo** [comment]
So you have one bug report. :)
Btw, I'm not personally using this module anyway.
