### ISSUE TITLE
Safe vs. aggressive option switcher

### ISSUE THREAD

**Issue by pepelsbey** [ben-eb/postcss-convert-values#14]
There are safe and _not that safe_ options available for value optimisations: `0.5em -> .5em` is quite safe, just like `500ms -> 1s`, but `52px -> 1pc` (random values) isn’t quite safe, [see discussion](https://github.com/jakubpawlowicz/clean-css/issues/654#issuecomment-138265027) in `clean-css`.

Currently there’s only one way to disable unsafe converion to physical values: disable this plugin comletely. But it also disables safe `.5em` optimisations:

```
// gulp.task(…
.pipe(nano({convertValues:false}))
```

Personally, I’d split such experimental and non-obvious optimisations into separate plugin (and disable it by default, read through [mentioned issue](https://github.com/jakubpawlowicz/clean-css/issues/654#issuecomment-139232127) carefully), but clear option like `unitConvertion:false` could be an option as well.

**Comment by TrySound** [comment]
@pepelsbey The only reason to use one plugin is performance issue. And I agree, we can add unit conversion option. But aggressive minification will still be enabled by default.

/cc @ben-eb

**Comment by ben-eb** [comment]
Lots of feedback on that issue. I'm happy to add an option to disable unit conversion between absolute length values, and make that the default.

**Comment by pepelsbey** [comment]
Great! Thank you for being more open than clean-css’ author.

**Comment by TrySound** [comment]
@pepelsbey convertUnit enabled by default on this plugin. For cssnano we will add safe option covering all plugins (convert-values and z-index now).

**Comment by pepelsbey** [comment]
Thank you!
