### ISSUE TITLE
border: 0 none is minified into invalid value

### ISSUE THREAD

**Issue by thetalecrafter** [ben-eb/postcss-convert-values#8]
`border: 0 none;` meaning `border-width: 0; border-style:none;`, gets minified to `border: 0 0;` which is invalid and gets ignored by browsers.

This can be minified to `border:0` or `border:none` to have the correct effect.

**Comment by ai** [comment]
@ben-eb I have same issue. I think it is very important, because can broke many sites.

**Comment by ben-eb** [comment]
Yup, @ai is correct. This is not handled by this module. https://github.com/ben-eb/cssnano/issues/20
